apiVersion: v1
kind: Service
metadata:
  name: chateex-service
spec:
  selector:
    app: chateex
  ports:
  - protocol: "TCP"
    name : http
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chateex-app
spec:
  selector:
    matchLabels:
      app: chateex
  replicas: 15
  template:
    metadata:
      labels:
        app: chateex
    spec:
      containers:
      - name: chateex
        image: docker.io/eliottelekkk/chateex:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000